apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-bootcamp
  labels:
    app: kubernetes-bootcamp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-bootcamp
  template:
    metadata:
      labels:
        app: kubernetes-bootcamp
    spec:
      containers:
      - name: kubernetes-bootcamp
        image: gcr.io/google-samples/kubernetes-bootcamp:v1
        # Ressources
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        # volumeMounts
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true

        env:
        # Define the environment variable
        # From ConfigMap
        - name: SCHOOL_NAME
          valueFrom:
            configMapKeyRef:
              name: app-conf
              key: GROUP_NAME
        # From Secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASSWORD

      # SideCar container
      - name: myapp-sidecar
        image: busybox:1.28
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']

      volumes:
      # You set volumes at the Pod level, then mount them into containers inside that Pod
      - name: config
        configMap:
          # Provide the name of the ConfigMap you want to mount.
          name: app-conf
          # An array of keys from the ConfigMap to create as files
          items:
          - key: "app.conf"
            path: "app.conf"

